# Copy to <delivery-collection>/pyproject.toml

[tool.black]
line-length = 88
target-version = ["py312"]
extend-exclude = '''
/(
  \.ansible
  | \.venv
  | \.cache
  | __pycache__
  | build
  | dist
)/
'''

[tool.pylint.main]
py-version = "3.12"
recursive = true
ignore-paths = [
  "^\\.ansible/.*$",
  "^\\.venv/.*$",
  "^\\.cache/.*$",
  "^__pycache__/.*$",
  "^build/.*$",
  "^dist/.*$",
]

[tool.pylint.messages_control]
disable = [
  "missing-module-docstring",
  "missing-class-docstring",
  "missing-function-docstring",
]

[tool.pylint.format]
max-line-length = 88
