---
- name: Ensure ansible_facts used by role
  ansible.builtin.setup:
    gather_subset: min
  when: >
    __rsyslog_forward_required_facts |
    difference(ansible_facts.keys() | list) | length > 0

- name: Set platform/version specific variables
  ansible.builtin.include_vars: "{{ __rsyslog_forward_vars_file }}"
  loop:
    - "{{ ansible_facts['os_family'] }}.yml"
    - "{{ ansible_facts['distribution'] }}.yml"
    - >-
      {{ ansible_facts['distribution'] }}_{{
      ansible_facts['distribution_major_version'] }}.yml
  loop_control:
    loop_var: __rsyslog_forward_vars_candidate
  vars:
    __rsyslog_forward_vars_file: >-
      {{ role_path }}/vars/{{ __rsyslog_forward_vars_candidate }}
  when: __rsyslog_forward_vars_file is file
